### ISSUE TITLE
Intresting

### ISSUE THREAD

**Issue by asonsgh** [stakewalker/hotnews#5]
it sounds intresting but how to use this? no Doc?

**Comment by stakewalker** [comment]
Hello, thank you for reaching me. This project doesn't have any documentation, and surely there's a lot of work to fix it and also leave it more understandable

But hotnews.py is the main file, and there's other files/modules to deal with video rendering and data parsing

Please check the comments in the files to track what's going on, and if you find it interesting maybe we could revive the old beast
